server:
  port: 9090

spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    encoding: utf-8
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.157.128:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Perfect@1314

logging:
  level:
    com.longlysmile.mapper: debug

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml